apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
  - name: rest
    protocol: TCP
    port: 1317
    targetPort: 1317
  - name: p2p
    protocol: TCP
    port: 26656
    targetPort: 26656
  - name: rpc
    protocol: TCP
    port: 26657
    targetPort: 26657
  selector:
    app: juno
  type: NodePort